version: '3.7'

services:
  databaseBlobenTest:
    image: 'postgres:13.6-bullseye'
    container_name: databaseBlobenTest
    env_file:
      - .env.test.local
    ports:
      - '9003:5432'

  redisTest:
    image: redis:6.2.6-bullseye
    container_name: redisTest
    ports:
      - '9081:6379'
