version: '3.7'

services:
  databaseBlobenTest:
    image: 'postgres:14.6-bullseye'
    container_name: databaseBlobenTest
    env_file:
      - .env.test.local
    ports:
      - '9003:5432'

  redisTest:
    image: redis:7.0.5-bullseye
    container_name: redisTest
    ports:
      - '9081:6379'

  caldav:
    image: bloben/caldav:latest
    ports:
      - "6080:80"
