version: '3.7'

services:
  databaseBlobenTest:
    image: 'postgres:13.7-bullseye'
    container_name: databaseBlobenTest
    env_file:
      - .env.test
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0.3-bullseye
    container_name: redis
    ports:
      - '6379:6379'

  caldav:
    image: bloben/caldav:latest
    ports:
      - "6080:80"
